### ISSUE TITLE
Publish to Terraform Registry

### ISSUE THREAD

**Issue by maveonair** [lxc/terraform-provider-incus#6]
Our Terraform provider should be published in the Terraform Registry, see [Publishing Providers](https://developer.hashicorp.com/terraform/registry/providers/publishing).

Open questions: 
 - @stgraber: To publish the package, we need to grant the Terraform Registry access to the lxc GitHub organization. We also need to create a signing key that will be used to publish the package. How would you like to proceed here?
 - How should we organize the versioning and changelog from now on? Incus started with 0.0.1 and so we could do the same here, but maybe start with 1.0.0?

**Comment by stgraber** [comment]
I'll take care of the registration bits for the provider and will initially put my GPG key in the registry so that should be fine. If someone else wants to handle releases in the future, we can add their GPG key too.

For versioning, I think we can probably release an initial 0.0.1 just to have something up, then make sure that all instructions and everything looks good and that there are no initial issues before putting out a 1.0.0? Unless Terraform cares about the specific version number somehow?

Incus is going to be doing 0.x until April or so when we'll jump straight to 6.0.0 to line up with LXC and LXCFS.

**Comment by stgraber** [comment]
https://registry.terraform.io/providers/lxc/incus/latest

**Comment by stgraber** [comment]
Let me know if there's any issue with it as it!

**Comment by maveonair** [comment]
Amazing! I just tried and it works perfectly :)!
